### ISSUE TITLE
Dashboard widgets not loading and giving timeout error

### ISSUE THREAD

**Issue by grafxflow** [rainlab/googleanalytics-plugin#107]
This is just an enquiry to see if anybody else is having timeouts on the dashboard with the google analytics widgets.

**Comment by LukeTowers** [comment]
@grafxflow do you have adblocker enabled? Is your property using the new version of Google Analytics (not supported)?

**Comment by grafxflow** [comment]
@LukeTowers Not sure yet if it's the hosting service, so will give it a few days and get back to you.

**Comment by mplodowski** [comment]
I have the same issue with website, where dashboard widgets were working fine until now.

I use the latest version of October 471 with Laravel 6 installed with composer and latest version of this plugin.

**Comment by datune** [comment]
@LukeTowers @grafxflow 

I was just about to report the same issue, I also narrowed down this problem to this extension (while enabled the dashboard has timeouts, when disabled, it does not happen).

**Comment by daftspunk** [comment]
Caused by third-party browser extension. Not much we can do about it but supply warnings to disable them
