### ISSUE TITLE
Update Guzzle library to version 7

### ISSUE THREAD

**Issue by dariopetraroia** [rainlab/googleanalytics-plugin#110]
Hy can you please update guzzle to last version?

I have conflicts with my root composer.json it require (^7.3).

Thank you

**Comment by PubliAlex** [comment]
Same here

![image](https://user-images.githubusercontent.com/55833027/168093011-07998e50-29ef-491c-b469-071874050b07.png)

**Comment by daftspunk** [comment]
This should be fixed in cbee476a1ea1b7191bc270d2ec9bdd5550c76932

Thanks!
