### ISSUE TITLE
GA4 support

### ISSUE THREAD

**Issue by kombimedia** [rainlab/googleanalytics-plugin#111]
Hi there,

Any plans to add GA4 support? Universal Analytics will no longer process new hits from 1st July 2023, so still a bit of time.

Cheers

**Comment by eddycodes** [comment]
I agree with @kombimedia Any plans to add GA4 support?

**Comment by daftspunk** [comment]
Yes, this is planned closer to the end date of GA3.

**Comment by eddycodes** [comment]
Thanks @daftspunk Looking forward to the update. And thanks for all the hard work on October!

**Comment by alekseybobkov** [comment]
Version 2.0.1 for Google Analytics 4 has been released today.

**Comment by kombimedia** [comment]
Great, thanks @alekseybobkov !
