### ISSUE TITLE
Forbidden error when adding dashboard widgets

### ISSUE THREAD

**Issue by chocolata** [rainlab/googleanalytics-plugin#114]
Hi,

For some reason I've been getting the following error when trying to add widgets to the dashboard:

`<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="x-ua-compatible" content="ie=edge"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <title>403 Forbidden</title> <link rel="stylesheet" href="/error_docs/styles.css"> </head> <body> <div class="page"> <div class="main"> <h1>Server Error</h1> <div class="error-code">403</div> <h2>Forbidden</h2> <p class="lead">You do not have permission to access this document.</p> <hr/> <p>That's what you can do</p> <div class="help-actions"> <a href="javascript:location.reload();">Reload Page</a> <a href="javascript:history.back();">Back to Previous Page</a> <a href="/">Home Page</a> </div> </div> </div> </body> </html>`

The weird thing is that this also happens with sites that previously succesfully added the Google Analytics widgets to the dashboard.

I'm using October CMS v3.6.18 and Google Analytics v2.0.3.

I know that this error could happen when you enter the wrong JSON-key or property ID or measurement ID, but I've triple checked it and as said, even sites that previously were configured correctly (and still display the widgets correctly) pop-up an error when trying to add any new widgets.

Could it be that something has become incompatible? Thanks for looking into it.

**Comment by daftspunk** [comment]
This is your server blocking the request, usually ModSec module for apache detecting a false-positive. You'd have to check the error logs to see what is causing it, or alternatively, relax the security rules.

**Comment by chocolata** [comment]
Hi Sam, thanks for this! This was exactly the issue. We have relaxed the security rules and now the widgets work perfectly. Thanks!
