### ISSUE TITLE
Unable to load private key

### ISSUE THREAD

**Issue by ardiansyah** [rainlab/googleanalytics-plugin#16]
hello, tanks for the plugin.

why I get "Unable to load private key" on all my analytisc reportwidget?
 i follow the  guide on documentation.

thanks.

**Comment by emzero** [comment]
Getting the same thing. 
There are 2 keys that can be downloaded from Google API.... a .json and a .p12...

**Comment by emzero** [comment]
@ardiansyah You need to use the .p12 key from Google API, not the .json.

**Comment by ardiansyah** [comment]
many thanks emzero, got my problem solved
