### ISSUE TITLE
P12 Certificate File Upload (Build 270)

### ISSUE THREAD

**Issue by SASniper** [rainlab/googleanalytics-plugin#17]
Hey there,

With the latest 270 build of October I am unable to upload .p12 certificate files for the Google Analytic plugin (version 1.0.3) within it's backend settings page.  The upload widget DropZone seems to be setup to only accept a restricted set of file types such as media or text.

I've tried adding `fileTypes: p12` to fields.yaml but the issue seems to run deeper into a nest of validation checks.  I couldn't find anywhere to declare a set of MIME types in order to pass validation.

Thanks

**Comment by daftspunk** [comment]
Fixed in 1.0.4 + Build 271
