### ISSUE TITLE
Error (403) User does not have sufficient permissions for this profile.

### ISSUE THREAD

**Issue by MicaelRodrigues** [rainlab/googleanalytics-plugin#20]
Hi,
I keep getting this error message on my dashboard:

*Error calling GET https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A15210611&start-date=30daysAgo&end-date=today&metrics=ga%3Avisits&dimensions=ga%3Adate: (403) User does not have sufficient permissions for this profile.*

I did all the steps as described, searched other solutions and anything seems to solve the problem.
What am i missing?

Cheers

<img width="675" alt="2" src="https://cloud.githubusercontent.com/assets/796443/9504703/f163fed4-4c35-11e5-942f-e5006ea1bd21.png">
<img width="903" alt="3" src="https://cloud.githubusercontent.com/assets/796443/9504707/f166f878-4c35-11e5-9f52-d6ec105cda98.png">
<img width="962" alt="4" src="https://cloud.githubusercontent.com/assets/796443/9504705/f1657354-4c35-11e5-80ff-7146d7f7ba5f.png">
<img width="352" alt="5" src="https://cloud.githubusercontent.com/assets/796443/9504706/f16555e0-4c35-11e5-9000-d1c6e67da5d2.png">

**Comment by 91337** [comment]
Have you been able to resolve the issue? I'm having it too.

**Comment by daftspunk** [comment]
I have heard there may be some replication time involved in the permissions, it should resolve itself within 10-15mins or so I'm guessing?

**Comment by MicaelRodrigues** [comment]
I'm having it for 4 days now, so...

**Comment by MicaelRodrigues** [comment]
Turns out, the *Account Id* (under Admin -> Account -> Account Settings) is not the correct number to use as your *Profile Id*. You have to use the specific *View Id* that you want to analyse. These may be the same, but they may also be different, as it is my case.
