### ISSUE TITLE
setting up per instructions causes dashboard to crash

### ISSUE THREAD

**Issue by hammy4785** [rainlab/googleanalytics-plugin#30]
I don't get any errors but following the instructions the dashboard won't load if there are any tables loaded for this plugin. Mind helping me out a bit?

**Comment by SaifurRahmanMohsin** [comment]
Same here. I get a `Google_Client::setClassConfig` error. Here’s a screenshot of the stack trace:

![Screenshot](http://i.imgur.com/rLOyrJ3.png)

**Comment by daftspunk** [comment]
Google's interface was recently updated, the instructions and code has been updated in v1.1.0. Please try again.
