### ISSUE TITLE
Error in widgets '{ "error" : "invalid_grant" }'

### ISSUE THREAD

**Issue by MaksimsGee** [rainlab/googleanalytics-plugin#35]
On each windget I have this error: Error refreshing the OAuth2 token, message: '{ "error" : "invalid_grant" }'

**Comment by Hessel91** [comment]
I have the same issue here..

**Comment by daftspunk** [comment]
Not sure what is causing this. I think it may have something to do with the P12 file.

**Comment by daftspunk** [comment]
This was a hairy one, fixed in v1.1.0 (d3d5d79759ba40d4a605314a572de2f10063abf3)
