### ISSUE TITLE
Autoload error on version 1.0.7

### ISSUE THREAD

**Issue by triasrahman** [rainlab/googleanalytics-plugin#36]
I just updated to latest version (1.0.7), but there is a error like this about autoload:

ErrorException in autoload.php line 25:
google-api-php-client's autoloader was moved to src/Google/autoload.php in 1.1.3. This redirect will be removed in 1.2. Please adjust your code to use the new location.

Any solution?

**Comment by daftspunk** [comment]
Is it fixed in v1.1.0 (d3d5d79759ba40d4a605314a572de2f10063abf3)?
