### ISSUE TITLE
"Version not supported"

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [rainlab/googleanalytics-plugin#37]
I just updated this to v1.1.0 and uploaded the new .json key file also checked that the Tracking Id as well as View ID are indeed correct. However, when I goto my dashboard I get this..

<img width="1440" alt="screen shot 2016-01-27 at 13 37 03" src="https://cloud.githubusercontent.com/assets/1699753/12607563/f0f934f2-c4fb-11e5-828d-8ea57e512beb.png">

I even tried deleting the service account and remaking it, adding Read & analyze permission to analytics but I still see this.

**Comment by daftspunk** [comment]
Please make sure you are running `v1.0.2` of the October.Drivers plugin too.

**Comment by SaifurRahmanMohsin** [comment]
That fixed it. Great thanks!
