### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate Even pointed to .PEM file

### ISSUE THREAD

**Issue by portal7** [rainlab/googleanalytics-plugin#42]
I followed all the steps mentioned in the section on troubleshooting. But I still see the same error.

I'm running PHP 5.6 on Windows 2012 with IIS 8 and the line of php.ini is:

Any idea what could be happening ?

PHP info Says....

openssl
OpenSSL support  enabled  
OpenSSL Library Version  OpenSSL 1.0.1i 6 Aug 2014  
OpenSSL Header Version  OpenSSL 1.0.1i 6 Aug 2014  
Directive Local Value Master Value 
openssl.cafile C:\Certificados\cacert.pem C:\Certificados\cacert.pem 
openssl.capath no value

**Comment by LukeTowers** [comment]
Closing due to lack of follow up
