### ISSUE TITLE
Wrong permissions

### ISSUE THREAD

**Issue by dzava** [rainlab/googleanalytics-plugin#44]
The plugin registers the [rainlab.googleanalytics.access_settings](https://github.com/rainlab/googleanalytics-plugin/blob/master/Plugin.php#L32) permission, but the settings register with the [rainlab.googleanalytics.settings](https://github.com/rainlab/googleanalytics-plugin/blob/master/Plugin.php#L73)

**Comment by vojtasvoboda** [comment]
Fixed by #45

Same issue as was https://github.com/rainlab/user-plugin/pull/161
