### ISSUE TITLE
InvalidAccessError on save

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/googleanalytics-plugin#53]
I'm getting an "Invalid Access Error" alert/error when hitting the save button in the Settings -> Analytics section of October. It seems to only occur on my client, because my colleague's client works fine.

It seems to be client bound and not account bound, because the same user accounts give the same error on my client and my user accounts works fine on other clients. 

Client: Safari
OS: OSX El Capitan
October: Build 351
Analytics Version: 1.2.1

**Comment by daftspunk** [comment]
This error is coming directly from the Google API, not from any October code. Just to confirm this, try copying the "working source code" to the environment where the error occurs.

**Comment by rafamem** [comment]
I have this error: Invalid argument supplied for foreach()

I think you have to update also the plugin tutorial :-/

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
