### ISSUE TITLE
Google Analytics Not Working

### ISSUE THREAD

**Issue by zukinaru** [rainlab/googleanalytics-plugin#57]
Dear Support,

I have installed Google Analytics Plugin, but still not receiving any hits/traffic when seeing it on Google Analytics Report.
Moreover, after see my page source code, i am not seeing any google analytics tracking code.

How to make sure/Test this plugin installation is Successfull ?

Note : i have uploaded json key, profile number and tracking id according to documentation.

Regards & Thanks,

Zuki

**Comment by jBOKA** [comment]
You have to add the tracker component to your layouts to include the tracking code to your pages

**Comment by daftspunk** [comment]
As above, see the documentation for this plugin for further information.
