### ISSUE TITLE
Missing Document information

### ISSUE THREAD

**Issue by ayumihamsaki** [rainlab/googleanalytics-plugin#58]
Hi,

I am not sure why but some information about this plugin in the october website seems missing now?

Could you please add to the document section the link to GA Events API please and give an example of setting up a custom one.

(This info use to be up there and now it seems missing???)

Anyway, it would be easier for people if it was added to the documentation page please.

Thanks.

(Off to search for the GA Events API page now...)

Rainlab I found the link you should add its this one: https://developers.google.com/analytics/devguides/reporting/core/v3/common-queries

**Comment by daftspunk** [comment]
Are you referring to the Support article OB-17? http://octobercms.com/blog/post/advanced-content-marketing-and-analytics

You can find this any time via the Support section here: http://octobercms.com/support

**Comment by ayumihamsaki** [comment]
Hi no I am not referring to that blog post. I am talking about this link: http://octobercms.com/plugin/rainlab-googleanalytics#documentation

You should add details here for people wanting to create custom GA Dashboard widgets in October.

Using this link: https://developers.google.com/analytics/devguides/reporting/core/v3/common-queries

I then found the dimension and metric values and was able to create a custom widget on my dashboard today.

I hope that makes a bit more sense what I am saying. You use to have instructions there a few months ago, I don't understand why it is suddenly missing now?

**Comment by daftspunk** [comment]
Are we talking about the same plugin? I'm not seeing a widget with these properties. However I am seeing one on the [Google Analytics extension plugin](https://github.com/scottbedard/analyticsextension/blob/a2349a97b7c28b27094ca81e014cc6ed240238a3/lang/en/lang.php#L21).

Perhaps you are thinking of this plugin: https://octobercms.com/plugin/bedard-analyticsextension
