### ISSUE TITLE
Permission Issue with any File Based RainLab Items

### ISSUE THREAD

**Issue by JREAM** [rainlab/googleanalytics-plugin#63]
Hi! I am having a permission issue with Rainlabs Blog (Viewing the Markdown, which I made a ticket for) and here the settings upload. I am clueless as to why this doesn't work!

- I am using HTTP2, so it's under SSL/443.
- I did a `setfacl` with Recursive Defaults, and Persistent Recursive Defaults for `www-data:www-data`, this works fine for everything. I do not make any files `777` rather its g+rw at the maximum, public can only read.
- Im running Ubuntu 16.04, PHP7, Apache2, nothing too fancy.

Might anyone know why this is happening? 
Thank you I hope to get this cool plugin to work!

![oct-perm](https://cloud.githubusercontent.com/assets/145959/25502486/b54b9c26-2b64-11e7-9659-06f12a047973.jpg)

**Comment by LukeTowers** [comment]
Closing due to lack of follow up.

**Comment by ametad** [comment]
I have had this problem as well. For me it was my adblocker plugin in the browser. When disabling the adblocker, the form works correct again.
