### ISSUE TITLE
Dashbord widget error

### ISSUE THREAD

**Issue by tiipiik** [rainlab/googleanalytics-plugin#65]
I'm having this error on the dashboard widgets 

> set the JSON service account credentials using Google_Client::setAuthConfig or set the path to your JSON file with the "GOOGLE_APPLICATION_CREDENTIALS" environment variable and call Google_Client::useApplicationDefaultCredentials to refresh a token with assertion.

It's probably due to a mistake of mine but can't find it. I've followed the instructions.

**Comment by LukeTowers** [comment]
Closing due to no further information provided.

**Comment by maartenmachiels** [comment]
I've encountered this too. Please make sure you have followed the exact instructions as provided in [the documentation] (https://octobercms.com/plugin/rainlab-googleanalytics). Also, take note of issue #20 , regarding the difference between Account ID and View ID. By taking that into account, I managed to get it up and running.
