### ISSUE TITLE
Ease configuration requirements for wider use

### ISSUE THREAD

**Issue by ametad** [rainlab/googleanalytics-plugin#66]
At the settings page it is not permitted to only set the Tracking ID and Domain Name. Because the Private Key and Profile ID are required:

![image](https://user-images.githubusercontent.com/1582541/27475262-c94ae9bc-5804-11e7-8ae0-22fbc0e97876.png)

I would like to use this plugin (the Tracker code component in particular) also when I don't have the Private Key and Profile ID yet. My clients not always are that quick with providing me with those data (key/id) and I want to start sending data from the website with the tracking code. 

Of course I could just hardcode the tracking code into the templates, but It would be nice to make this a 'config only' thingy. Where I would have set up the component in the templates and the dashboard ready, the only thing needed should be fill out the configuration correctly.

**So my main 'feature request' is: can the validation 'required' be dropped of Private Key and Profile ID?**

```
    /**
     * Validation rules
     */
    public $rules = [
        'gapi_key'   => 'required',
        'profile_id'   => 'required'
    ];
```

**Comment by LukeTowers** [comment]
I don't see a problem with it, @daftspunk any input?
