### ISSUE TITLE
getting error count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by bkrajendra** [rainlab/googleanalytics-plugin#74]
Im getting error on dashboard report widget.

```
count(): Parameter must be an array or an object that implements Countable

```

Looks like PHP7.+ requirement. Where it can be wrong.?
I searched for count()... corrected it... but it does not solve the issue.
please help

**Comment by LukeTowers** [comment]
PHP 7.1+ to be specific. What is the full stack trace?

**Comment by alxy** [comment]
I can confirm this bug, and it appears to be on PHP7.1+ indeed.

**Comment by alxy** [comment]
I was able to fix this. The error originated from a clash of Guzzle dependencies. I have used Guzzle in different plugins, and october apparently loaded an older version from one of my other plugins. So @bkrajendra make sure you are on ``"guzzlehttp/guzzle": "~6.0"``
