### ISSUE TITLE
Error when saving backend settings

### ISSUE THREAD

**Issue by Alex360hd** [rainlab/googleanalytics-plugin#76]
Hello,

Recently, google analytics plugin displayed an error popup when I try to save the settings in the backend.

It just instantly display a popup, with word "Error" in it. No event logs, nothing that could help me to debug.

I use this plugin since long time, never had problems before, and now I get it on all new projects. On the same server than before.

Don't know what to do as I don't have any logs, if somebody can point me something to do to get more informations...

Thanks

Alex

**Comment by cloudwales** [comment]
It seems its an error with Firefox. I had this issue and used Chrome and all worked

**Comment by LukeTowers** [comment]
@cloudwales thanks for the update! Ad blockers can be pretty aggressive blocking any URLs that contain ad keywords and/or google analytics
