### ISSUE TITLE
problems with the setup

### ISSUE THREAD

**Issue by slaapkopamy** [rainlab/googleanalytics-plugin#83]
Hi there,

I tried yesterday to setup the plugin on my panel but seems like there is an issue with permissions. I don't know what it cause or what kinda problem it is but tried everything what i could do but keeps posting this error message: 

"{"error":{"errors":[{"domain":"global","reason":"insufficientPermissions","message":"User does not have sufficient permissions for this profile."}],"code":403,"message":"User does not have sufficient permissions for this profile."}}"

what and where do i miss the permissions? is it in google analytics self or is the from the api? 🤔

**Comment by w20k** [comment]
@slaapkopamy my guess this might be Google Analytics Error. Try playing with permissions or ask your supervisor/owner (if that's the case) to generate code for you.

**Comment by slaapkopamy** [comment]
> @slaapkopamy my guess this might be Google Analytics Error. Try playing with permissions or ask your supervisor/owner (if that's the case) to generate code for you.

do i need some special perms / roles on the service account by making the account in de google api console?

**Comment by bennothommo** [comment]
@slaapkopamy You will need the *Read & Analyse* permission to the Google Analytics property for the user account that the Google Analytics API is linked to. If you do not know how to set this up, I would suggest either referring to the [README](https://github.com/rainlab/googleanalytics-plugin/blob/master/readme.md) or looking up the Google Analytics help docs for answers.
