### ISSUE TITLE
GDPR: do not track if user did not opt in

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/googleanalytics-plugin#87]
Hi guys, quick question, not really about the plugin itself, but on a higher level. I was hoping to get your views on this.

In Europe we have to follow the GDPR regulation. This means that we have to get the formal and unambiguous opt-in of users to track them via tracking cookies. Though there still is a grey area, I would like to start working on a foolproof solution. 

What I thought about doing was to put a banner at the bottom of the site with a question: "Do you agree to be tracked: yes or no". When the user clicks "yes" a cookie is set. I would then test for this cookie in my layout, and only if the cookie is present, I would include the Rainlab Google Analytics partial. 

What are your views on this? Do you think this is a fitting solution? Thanks in advance.

**Comment by Eoler** [comment]
> What are your views on this? Do you think this is a fitting solution? Thanks in advance.

Yes it is. You can use existing plugins, this one has handy GA example:
https://github.com/OFFLINE-GmbH/oc-gdpr-plugin#gdprcookieallowedcode-minlevel--0

**Comment by maartenmachiels** [comment]
Hi Eoler, thank you so much for your answer. The provided link does look very fitting. Is it compatible with the Rainlab Google Analytics plugin?

**Comment by Eoler** [comment]
> Is it compatible with the Rainlab Google Analytics plugin?

Yes, just swap GA include comment with a component reference.

**Comment by maartenmachiels** [comment]
Perfect, thank you!
