### ISSUE TITLE
Google Analytics - User does not have any Google Analytics account.

### ISSUE THREAD

**Issue by fayazv** [rainlab/googleanalytics-plugin#89]
After installing and configuring the plugin. When adding the widgets to the dashboard. I get the following error messages on the widgets.

```
{"error":{"errors":[{"domain":"global","reason":"insufficientPermissions","message":"User does not have any Google Analytics account."}],"code":403,"message":"User does not have any Google Analytics account."}}
```

**Comment by LukeTowers** [comment]
Double check your configuration and try on a fresh install.

**Comment by fayazv** [comment]
I have done fresh install 3 times and getting the same error. What could be the issue?

**Comment by LukeTowers** [comment]
@fayazv are you sure you've followed the steps here: https://github.com/rainlab/googleanalytics-plugin#configure-the-api exactly?

**Comment by fayazv** [comment]
Yes have used that documentation to setup.

**Comment by LukeTowers** [comment]
And you're positive that the user you used to follow the instructions does actually have a Google Analytics account?

**Comment by fayazv** [comment]
Yes I'm positive. I have also added 2 more accounts as owners with read & analyze access.

**Comment by LukeTowers** [comment]
@w20k or @bennothommo can either of you confirm this issue?

**Comment by bennothommo** [comment]
@LukeTowers Just tried it out on a fresh install - no issues here. I did copy the wrong Account ID at one stage and got an error similar to the one @fayazv (although it said "User has insufficient permissions") - this was after I copied it from the Property settings, and not the View settings in Google Analytics.

**Comment by w20k** [comment]
@LukeTowers can also confirm works perfectly fine on a fresh install!

**Comment by LukeTowers** [comment]
@fayazv I'm afraid that we can't do anything to help you unless we can reproduce the issue. It sounds like a misconfiguration on your end with some combination of your plugin configuration / Google Analytics account.
