### ISSUE TITLE
Plugin doesn't work with php 7.4 please update

### ISSUE THREAD

**Issue by ayumi-cloud** [rainlab/googleanalytics-plugin#92]
I'm seeing this message: 

```
Deprecated: implode(): Passing glue string after array is deprecated
```

In the dashboard widgets, see below for example:

![image](https://user-images.githubusercontent.com/57409060/69903372-1fec0000-1390-11ea-958a-c51d42619c6f.png)

The problem that the previous versions of implode allowed the array and glue string parameters in either order. 7.4 is more precise on the order of parameters. The old way that could work before was:

```php
<?php
$data = [
'Apple',
'Orange',
'Pear,
];
implode($data, ',');
```

To fix it, simply swap the variables for future versions of php.

```php
<?php
$data = [
'Apple',
'Orange',
'Pear
];
implode(',' , $data);
```

**Comment by LukeTowers** [comment]
@ayumi-cloud submit a PR and I'll review it.

**Comment by ayumi-cloud** [comment]
- I think this error is coming from October CMS side and not this plugin.
