### ISSUE TITLE
php 7.4 implode(): Passing glue string after array is deprecated. Swap the parameters

### ISSUE THREAD

**Issue by Hessel91** [rainlab/googleanalytics-plugin#93]
Hi, since I updated my website to php 7.4 all dashboard widgets return this error:
implode(): Passing glue string after array is deprecated. Swap the parameters

Is there a temporary work around until October is ugraded with laravel 6?

**Comment by LukeTowers** [comment]
@Hessel91 what version of October are you using? What other plugins are you using? Are you using Composer?

**Comment by Hessel91** [comment]
@LukeTowers  Systeem build 464
using:
![Image 8](https://user-images.githubusercontent.com/7326568/72396020-a50e5700-373b-11ea-815f-8c7e8676ccf5.jpg)

not using composer.

**Comment by LukeTowers** [comment]
@Hessel91 what's the full stack trace in the error log?

**Comment by MilosStanic** [comment]
Also got this, and there is no stack trace on the error. It is just shown in the Dashboard like this:
![Screenshot_278](https://user-images.githubusercontent.com/3983854/75873884-0506ad00-5e11-11ea-9c9b-aceff900b8ee.png)

**Comment by igor-tv** [comment]
I am trying to connect Google Analytics for the first time, and the settings do not accept the private key file. I also have PHP 7.4. CURRENT BUILD 464

On PHP 7.3, the same installation works fine.

**Comment by datune** [comment]
@LukeTowers I can confirm this issue. 

I looked into it, and it seems that the problem is with the vendor libraries, phpseclib as well as psr. They did not follow the recommendation for the order of the parameters: glue, string. Instead opting to code it reversed. 

PHP7.4 does not allow for this.

**Comment by LukeTowers** [comment]
@datune are there any issues for this in those libraries?

**Comment by grafxflow** [comment]
I have updated the following and all their dependancies and it's now working fine in PHP7.4, but has not been tested in PHP versions below this.

"google/apiclient-services": "^0.129.0",
"google/auth": "^1.8",
 "google/apiclient": "^2.4"

**Comment by grafxflow** [comment]
Okay I can clarify I have tested the changes in vagrant boxes with the following versions of php with no issues part from this initially **Loading from cache** - see below which was sorted.

```
OctoberCMS Build 465
```
```
PHP version: 7.0.22-0ubuntu0.16.04.1
```

And

```
PHP version: 7.1.10-1+ubuntu16.04.1+deb.sury.org+1
```

There was one issue with... 

```
Problem 1
    - monolog/monolog 2.0.2 requires php ^7.2 -> your PHP version (7.1.10) does not satisfy that requirement.
    - monolog/monolog 2.0.2 requires php ^7.2 -> your PHP version (7.1.10) does not satisfy that requirement.
    - Installation request for monolog/monolog (locked at 2.0.2) -> satisfiable by monolog/monolog[2.0.2].
```

But then I ran this which sorted the issue in relation to **Loading from cache**.

```
composer clear-cache
composer update
```

> **NOTE:** These commands were being called from vagrant box terminal **vagrant@damianlewis:**

**Comment by marco-silvestri** [comment]
> I looked into it, and it seems that the problem is with the vendor libraries, phpseclib as well as psr. They did not follow the recommendation for the order of the parameters: glue, string. Instead opting to code it reversed.
> 
> PHP7.4 does not allow for this.
