### ISSUE TITLE
Analytics live view doesn't work when using component

### ISSUE THREAD

**Issue by Somel1978** [rainlab/googleanalytics-plugin#95]
Tried to get support through slack 
No luck.

Plugin installed properly no errors.
No data is being captured on dashboards widgets, no data is being sent to google.
Used component as instructed by documentation.

Unclear how to troublesoot this.

**Comment by LukeTowers** [comment]
Have you followed the instructions on configuring the API here: https://github.com/rainlab/googleanalytics-plugin#configuration?

**Comment by Somel1978** [comment]
Hi Luke,

Yes to the letter.

Not sure why is not working.

**Comment by LukeTowers** [comment]
Is debug mode enabled?

**Comment by Somel1978** [comment]
Yes.

**Comment by Somel1978** [comment]
![image](https://user-images.githubusercontent.com/35574432/79531387-1c6cc300-806a-11ea-8f0f-3258d17fcf89.png)

**Comment by Somel1978** [comment]
that's the output of the widgets

**Comment by Somel1978** [comment]
![image](https://user-images.githubusercontent.com/35574432/79532329-a74ebd00-806c-11ea-9994-24e6bc0005c1.png)

This google check on code and it seems ok

**Comment by Somel1978** [comment]
![image](https://user-images.githubusercontent.com/35574432/79532637-99e60280-806d-11ea-8b23-02f7d94fca2c.png)
Analytics settings

**Comment by Somel1978** [comment]
![image](https://user-images.githubusercontent.com/35574432/79532733-e16c8e80-806d-11ea-973e-ae8fc06d5516.png)

settings in October CMS

**Comment by LukeTowers** [comment]
Do you have other server error logs you can check?

**Comment by Somel1978** [comment]
Not on octobercms.

I can ask the system admin to see if there is any error on the windows
server.
What should we look for?

**Comment by LukeTowers** [comment]
Look for the server software's error logs, or any PHP specific error logs.

**Comment by Somel1978** [comment]
Luke

As soon I replaced the component and used google analytics code instead it
started working.

Nothing on the server logs.

**Comment by LukeTowers** [comment]
What do you mean by replaced the component?

**Comment by Somel1978** [comment]
Removed it from the pages....

You have two options

A) using the component on the layout after %pages%
B) do not use the component and use the js script code provided per google.

Method a) as it is described on the documentation do not work for me.

This led me to believe that something on the component code does not work
with the universal analytics. Its a brand new analytics account.

It also let me to consider that on the settings you could add a place to
paste the google provided code instead of using some thing generic. Just a
thought.

**Comment by LukeTowers** [comment]
@Somel1978 could you paste the code that Google provided along with where Google told you to put it on your page?

**Comment by Somel1978** [comment]
` 
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxxxx989-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-xxxxxx989-1');
</script>`

masked the UA for privacy

**Comment by LukeTowers** [comment]
@Somel1978 did you try putting the component in the HEAD section?

**Comment by Somel1978** [comment]
Think so, but not certain to be honest as instructions were to place it
below pages.

**Comment by LukeTowers** [comment]
Could you give it a try? Perhaps we need to update the instructions. In theory it should work either place, putting it in the HEAD just prioritizes it above everything else, which is why Google recommends it there, and we recommend not putting it there.

**Comment by Somel1978** [comment]
Luke,
Carried the following to ensure proper testing
- Created three new layout templates
  -  Template a uses google code on the head
  -  Template B uses component in Body after pages
  -  Template C uses component in Head

Results: 
Templates with a head section properly display in google analytics real time view.
Template with component in Body does not show up in google analytics real time view
Template with component in Body does show up after 48h in google analytics

So most like has to do how analytics tracks coding?
Not sure what to think now.
Can it be something with new accounts?
Did end up testing google code at end of body but this was also visible in real time view, what confused me more. I suspect the only thing the component does is add the script?

**Comment by LukeTowers** [comment]
@Somel1978 ah, I see. https://github.com/rainlab/googleanalytics-plugin/blob/master/components/tracker/default.htm is using a pretty old version of the tracking code. You could probably update it in a PR to use the new code that Google is suggesting and then the component would work for realtime viewing too.

**Comment by Somel1978** [comment]
Not a coder.
Not sure what you mean lol

**Comment by LukeTowers** [comment]
That's fine :) 

@mjauvin or @bennothommo could you look at updating the GA snippet we use in the component in a way that retains our current options (forceSSL & annomizeIP)?

**Comment by Eoler** [comment]
> could you look at updating the GA snippet we use in the component in a way that retains our current options (forceSSL & annomizeIP)?

@LukeTowers here you go: #100
