### ISSUE TITLE
cURL error 77

### ISSUE THREAD

**Issue by dijodill** [rainlab/googleanalytics-plugin#96]
Hi,

Greetings of the day!!

I tried integrating google analytics to my website, after following the documentation of google analytics plugin, I got the following error:

**cURL error 77: error setting certificate verify locations: CAfile: /etc/pki/tls/certs/ca-bundle.crt CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)**

My site dont have ssl certificate.

Somebody please help me resolve this.

Thanks in advance.

**Comment by LukeTowers** [comment]
Sounds more like there's a problem with your server configuration such that cURL can't access a HTTPS URL, not that your site itself needs to support HTTPS. Try contacting your hosting provider.

**Comment by dijodill** [comment]
> Sounds more like there's a problem with your server configuration such that cURL can't access a HTTPS URL, not that your site itself needs to support HTTPS. Try contacting your hosting provider.

Thank you so much. I changed the php version to 7.2 and it worked.
