### ISSUE TITLE
Blog metrics

### ISSUE THREAD

**Issue by dijodill** [rainlab/googleanalytics-plugin#97]
Hi,

This is not an issue. 

I'm new to webdevelopment and also to october cms.

I would like to know how to track blog posts in october cms like views for each blogs, time on page, etc…

I could only do this using these plugins(Google Analytics, Google Analytics Extension).

![Screenshot (35)](https://user-images.githubusercontent.com/42942022/83360171-e0cd5480-a39c-11ea-9e65-c3c5ad3315f2.png)

But all I want is to filter the results only to blogs.

My blog url is like Mydomain.com/blog/my-first-post

Any help will be greatly appreciated!

Thanks in advance.

**Comment by grafxflow** [comment]
So maybe a search field option in the widget.

But can this be passed to google analytics for the results?

**Comment by dijodill** [comment]
> So maybe a search field option in the widget.
> 
> But can this be passed to google analytics for the results?

I dont know whether this is the best way to do it, but I simply created another widget within rainlab's google analytics widget folder which filters only blog pages.
