### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError: Undefined class constant 'VERSION'

### ISSUE THREAD

**Issue by zakir1929** [rainlab/googleanalytics-plugin#98]
Hi I am having a problem 

```
Symfony\Component\Debug\Exception\FatalThrowableError: Undefined class constant 'VERSION' in
```

Steps to reproduce:

=>  install any plugin which has a guzzlehttp 7.0 version in it. (I created a small custom plugin and installed guzzle via composer)

=> now Install Rainlab.GA plugin and configure it from the setting page.

=> now come to the admin dashboard and add google analytics widget.

You will see that error.

 What I think is that this problem comes because of Rainlab.GA has a guzzlehttp 6.5 version installed and but since namespaces are the same in both plugin and Rainlab.GA is trying to access my plugin guzzlehttp which is on the 7.0 version.

Can you please tell me what to do with this namespace problem.

**Comment by LukeTowers** [comment]
You can't use two different versions of a dependency at the same time. I recommend that you switch to using a plugin that uses Guzzle 6.0 instead.

**Comment by zakir1929** [comment]
@LukeTowers Ok, I able to solve it in that way for now. but I think it's a big problem with octobercms.

suppose I install 2 different plugins from octobercms marketplace and both have 2 dependencies but with different versions. then there will be a conflict and the website will have an error.

nevertheless, Thankyou for your reply. at least right now I don't have this issue anymore.

**Comment by LukeTowers** [comment]
@zakir1929 it's not a problem with October, it's a problem with dependencies in general. There's no easy way to load two different versions of the same dependency at the same time without having problems.

**Comment by zakir1929** [comment]
@LukeTowers yes you are right. I understand your point

Thanks !!!
